---
- hosts: 172.31.42.168
  become: yes
  tasks: 
  - name: install git
    apt:
      name: git
      state: present

  - name: install wget
    apt:
      name: wget
      stateee: present
    ignore_errors: yes


