---
- hosts: 172.31.42.168
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: create myfolder
    file:
      path: /home/ubuntu/myfolder
      state: directory
  - name: copy file from master to node side
    copy:
       src: my2nfile.txt
       dest: /home/ubuntu/my2ndfile
  - name: install apache2 
    apt:
      name: apache2
      state: present

      