---
- hosts: 172.31.42.168
  become: yes
  tasks: 
  - include_tasks: myfile.yml
  - name: create myfolder
    file:
      path: /home/ubuntu/myfolder
      state: directory
  - name: copy file from master to node side
    copy:
       src: my2nfile.txt
       dest: /home/ubuntu/my2ndfile
  - name: install apache2 
    apt:
      name: apache2
      state: present
  
  - name: download remote (internet file)
    get_url:
      url: https://maha22aug22.s3.us-east-2.amazonaws.com/mahaLogin.war
      dest: /home/ubuntu/mahaLogin.war
      force_basic_auth: yes

  - name: copy dynamic file into side 
    template:
        src: myindex.j2
        dest: /var/www/html/index.html
    notify: restartwebserver
    
  handlers:
  - name: restartwebserver
    service:
       name: apache2
       state: restarted
